steps:
  # 1. Install dependencies
  - name: 'node:20'
    id: 'install-dependencies'
    entrypoint: 'npm'
    args: ['install']

  # 2. Build and deploy Firebase functions
  - name: 'ghcr.io/genesys/multi-cloud/firebase-cli:latest'  # Updated Firebase image
    id: 'deploy-firebase-functions'
    entrypoint: 'firebase'
    args:
      - 'deploy'
      - '--only'
      - 'functions'
      - '--project'
      - '$PROJECT_ID'
      - '--non-interactive'
      - '--token'
      - '$_FIREBASE_TOKEN'

  # 3. Build and push backend container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloud-explorer-backend:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile.prod'
      - '.'  # Build context set to root directory

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cloud-explorer-backend:$COMMIT_SHA'

  # 4. Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloud-explorer-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cloud-explorer-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # 5. Build React Native app for Android
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-android-builder-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/react-native-builder:latest'
      - '-f'
      - 'android/Dockerfile.builder'
      - '--network=cloudbuild'  # Add network access
      - './android'

  - name: 'gcr.io/$PROJECT_ID/react-native-builder:latest'
    id: 'build-android-app'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd android && ./gradlew assembleRelease

  # 6. Upload APK to Google Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'upload-apk'
    entrypoint: 'gsutil'
    args:
      - 'cp'
      - 'android/app/build/outputs/apk/release/app-release.apk'
      - 'gs://$PROJECT_ID-builds/cloud-explorer-$COMMIT_SHA.apk'

images:
  - 'gcr.io/$PROJECT_ID/cloud-explorer-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/react-native-builder:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true  # Enable environment variable substitution

timeout: '3600s'

artifacts:
  objects:
    location: 'gs://$PROJECT_ID-builds/'
    paths: ['android/app/build/outputs/apk/release/app-release.apk']