import { Timestamp } from 'firebase-admin/firestore';
import { LearningProgress } from './LearningProgress';
import { UserSettings } from './UserSettings';


export interface User {
  uid: string; // Unique ID generated by Firebase Authentication
  email: string;
  displayName: string;
  photoURL?: string; // URL to the user's profile picture (optional)
  createdAt: Timestamp; // When the user registered
  lastLogin?: Timestamp; // Last login time
  learningProgress: LearningProgress;
  settings: UserSettings;
}
