export interface User {
userId: string, // Unique ID generated by Firebase Authentication
  email: string,
  displayName: string,
  photoURL: string, // URL to the user's profile picture
  createdAt: Date, // When the user registered
  lastLogin: Date, // Last login time
  learningProgress: {
    completedModules: [], // Array of module IDs the user has completed
    completedQuizzes: [], // Array of quiz IDs the user has completed
    completedExams: [], // Array of exam IDs the user has completed
    score: number, // Overall score across quizzes and exams
  },
  settings: {
    notificationsEnabled: boolean,
    darkMode: boolean,
  }
}
